version: '3.7'

services:
  # Django app service
  django:
    build: .
    container_name: mountainlionmovies
    volumes:
      - .:/app
    expose:
      - "8000"  # This exposes the app on port 8000 but does not map to the host
    environment:
      - DJANGO_SETTINGS_MODULE=mountainlionmovies.settings

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # Exposes Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
